//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 10:48:27 AM EDT 
//


package com.amb.splitteraggregator.product.jaxb.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amb.splitteraggregator.product.jaxb.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amb.splitteraggregator.product.jaxb.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PRODUCTRESPONSE }
     * 
     */
    public PRODUCTRESPONSE createPRODUCTRESPONSE() {
        return new PRODUCTRESPONSE();
    }

    /**
     * Create an instance of {@link PRODUCTRESPONSE.PRODUCTRESPONSEDATA }
     * 
     */
    public PRODUCTRESPONSE.PRODUCTRESPONSEDATA createPRODUCTRESPONSEPRODUCTRESPONSEDATA() {
        return new PRODUCTRESPONSE.PRODUCTRESPONSEDATA();
    }

    /**
     * Create an instance of {@link PRODUCTRESPONSE.ERROR }
     * 
     */
    public PRODUCTRESPONSE.ERROR createPRODUCTRESPONSEERROR() {
        return new PRODUCTRESPONSE.ERROR();
    }

    /**
     * Create an instance of {@link PRODUCTRESPONSE.PRODUCTRESPONSEDATA.PRODUCT }
     * 
     */
    public PRODUCTRESPONSE.PRODUCTRESPONSEDATA.PRODUCT createPRODUCTRESPONSEPRODUCTRESPONSEDATAPRODUCT() {
        return new PRODUCTRESPONSE.PRODUCTRESPONSEDATA.PRODUCT();
    }

}
